version: '3'

services:
  drupal:
    build:
      context: .
      dockerfile: dockerfile-drupal
    image: drupal-custom
    ports:
      - "80:80"
    volumes:
      - ./drupal:/var/www/html
    environment:
      DRUPAL_DB_HOST: db
      DRUPAL_DB_NAME: drupal
      DRUPAL_DB_USER: drupaluser
      DRUPAL_DB_PASSWORD: your_password
    depends_on:
      - db

  db:
    build:
      context: .
    image: mariadb
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupaluser
      MYSQL_PASSWORD: your_password
