version: '3'

services:
  drupal:
    build:
      context: .
      dockerfile: dockerfile-drupal
    image: drupal-custom
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./web:/var/www/html:rw
      # - ../letsencrypt:/etc/letsencrypt
      - ./apache:/etc/apache2/sites-available
      - /etc/letsencrypt/live/ericsdrupalportfolio.com:/etc/letsencrypt/live/ericsdrupalportfolio.com:ro
      - /etc/letsencrypt/archive/ericsdrupalportfolio.com:/etc/letsencrypt/archive/ericsdrupalportfolio.com:ro
      - /etc/letsencrypt/renewal/ericsdrupalportfolio.com.conf:/etc/letsencrypt/renewal/ericsdrupalportfolio.com.conf:ro      
    environment:
      DRUPAL_DB_HOST: db
      DRUPAL_DB_NAME: drupal
      DRUPAL_DB_USER: drupaluser
      DRUPAL_DB_PASSWORD: your_password
      IS_LIGHTSAIL_ENV: 'true'  # Set this to include the Lightsail-specific settings
    depends_on:
      - db

  db:
    image: mariadb:10.5
    ports:
      - "3306:3306"
    volumes:
      # - ./database:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupaluser
      MYSQL_PASSWORD: your_password

volumes:
  db_data: